services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  hotel-service:
    build: ./hotel-service
    container_name: hotel-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - HOTEL_DB_URL=jdbc:h2:mem:hoteldb

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - hotel-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - BOOKING_DB_URL=jdbc:h2:mem:bookingdb
      - BOOKING_JWT_SECRET=very-secret-signing-key-change-me
